dark-mode: true
pretty: true
gitignore: true
# auto-commits: false
# dirty-commits: false
anthropic-api-key: # put your anthropic api key here
api-key: # put your openrouter key here
set-env:
  - OLLAMA_API_BASE=http://127.0.0.1:11434
